name: PluginTest
version: '${project.version}'
main: me.maksasutka.plugintest.PluginTest
api-version: '1.20'
author: maksas
description: test plugin
website: https://github.com/maksasGit
commands:
  sb:
    description: Open your scoreboard